name: Tests

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run unit tests
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies 
        run: npm install
      
      - nane: Install playwright
        run: npx playwright install
        
      - name: Start tests
        run: npm test