name: Tests

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Run unit tests
    timeout-minutes: 3
    runs-on: debian-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16"

      - name: Intall dependencies 
        run: npm install
      
      - name: Start tests
        run: npm test